# Generated by Django 5.2.11 on 2026-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL')], max_length=20)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
