# Generated by Django 5.2.11 on 2026-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_agent_ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('system', 'Système')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dbsource',
            name='status',
            field=models.CharField(choices=[('connected', 'Connectée'), ('error', 'Erreur'), ('disconnected', 'Non connectée')], default='disconnected', max_length=20),
        ),
    ]
