# Generated by Django 5.2.11 on 2026-02-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_datasource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='status',
        ),
    ]
