# Generated by Django 5.2.11 on 2026-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_agent_ai_alter_dbsource_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'Agent")),
                ('model_name', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Rapide)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (Avancé)')], default='gemini-2.5-flash', max_length=50)),
                ('system_instruction', models.TextField(blank=True, help_text='Instructions de rôle (ex: Tu es un expert en Python)')),
                ('is_active', models.BooleanField(default=False, help_text='Cochez pour définir comme agent par défaut')),
            ],
        ),
    ]
