# Generated by Django 5.2.11 on 2026-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_datasource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
