# Generated by Django 5.2.11 on 2026-05-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_agent_ai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent_Ai',
            new_name='Agent',
        ),
    ]
