# Generated by Django 5.2.11 on 2026-02-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_agent_ai_response_agent_ai_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response_agent_aI',
        ),
    ]
