# Generated by Django 5.2.11 on 2026-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_agent_ai_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(blank=True, choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Rapide)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (Avancé)')], default='gemini-2.5-flash', max_length=50),
        ),
    ]
