# Generated by Django 5.2.11 on 2026-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_agent_model_name_alter_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name="Nom de l'Agent"),
        ),
    ]
