# Generated by Django 5.2.11 on 2026-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key',
            field=models.TextField(default=False, help_text="La clée de l'API", max_length=1000),
        ),
    ]
