# Generated by Django 5.2.11 on 2026-05-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_agent_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.TextField(default='', help_text="La clée de l'API", max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_instruction',
            field=models.TextField(blank=True, help_text='Instructions de rôle (ex: Tu es un expert en Python)', null=True),
        ),
    ]
