# Generated by Django 5.2.11 on 2026-06-17 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_agent_api_key_alter_agent_system_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_instruction',
            field=models.TextField(blank=True, default='', help_text='Instructions de rôle (ex: Tu es un expert en Python)'),
            preserve_default=False,
        ),
    ]
