# Generated by Django 5.2.11 on 2026-06-17 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_agent_date_creation_alter_agent_system_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dbsource',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbsource',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
