# Generated by Django 5.2.11 on 2026-06-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_agent_date_modification_dbsource_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('system', 'Système Interne')], max_length=20, verbose_name='Fournisseur')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], max_length=10, verbose_name='Statut')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name="Code d'erreur/Retour")),
                ('prompt_sent', models.TextField(verbose_name='Prompt envoyé')),
                ('response_received', models.TextField(blank=True, null=True, verbose_name="Réponse brute ou JSON d'erreur")),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens totaux')),
                ('execution_time', models.FloatField(default=0.0, verbose_name="Temps d'exécution (secondes)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'appel")),
            ],
            options={
                'verbose_name': 'Log API IA',
                'verbose_name_plural': 'Logs API IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
