# Generated by Django 5.2.11 on 2026-06-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_aiapilog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_agent_ai',
            old_name='timestamp',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='message_ai',
            old_name='timestamp',
            new_name='date_creation',
        ),
    ]
